language: go

go:
  - 1.5.3
  - 1.6
# - tip # NOTE: disabled - see https://github.com/travis-ci/gimme/issues/38

install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/golang/lint/golint

script:
  - go test -v ./...
  - go vet ./...
  - GOFMT=$(gofmt -d -s .) && echo $GOFMT && test -z "$GOFMT"
