runtime: go
vm: true

automatic_scaling:
  min_num_instances: 1

#[START env]
env_variables:
  # See https://github.com/go-sql-driver/mysql
  MYSQL_CONNECTION: user:password@tcp([host]:3306)/dbname
#[END env]
