runtime: go
vm: true

automatic_scaling:
  min_num_instances: 1

#[START env_variables]
env_variables:
  GCLOUD_DATASET_ID: your-project-id
#[END env_variables]

# Temporary workaround to authorize this application to access Cloud Datastore.
# Remove when cloud/datastore is backed by datastore/v1beta3.
beta_settings:
  service_account_scopes: >
    https://www.googleapis.com/auth/userinfo.email,
    https://www.googleapis.com/auth/cloud-platform
